spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: Geroller447352096
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  file:
    name: logs/online-store.log
  level:
    root: INFO
    phoug.store: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: ERROR
    org.apache.catalina: ERROR

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    version: openapi_3_0
